version: "3"

#networks:
#  mynetwork:
#    ipam:
#      driver: default
#      config:
#        - subnet: 182.17.0.0/16
#          gateway: 182.17.0.1

networks:
  mynetwork:
    external:
      name: bit-env_mynetwork

services:
  das-account-indexer:
    container_name: das-account-indexer-svr
    build:
      context: ./das-account-indexer
      dockerfile: Dockerfile
    image: das-account-indexer
    restart: always
    working_dir: /app
    entrypoint: [ "/app/das-indexer", "--config", "/app/config/config.yaml" ]
    ports:
      - "8121:8121"
      - "8122:8122"
      - "8123:8123"
    volumes:
      - ./das-account-indexer/config:/app/config
    networks:
      - mynetwork


# docker-compose -f docker-compose-indexer.yaml up
# docker build .
# docker logs -f --tail=10 das-indexer-svr