version: "3"

#networks:
#  mynetwork:
#    ipam:
#      driver: default
#      config:
#        - subnet: 182.17.0.0/16
#          gateway: 182.17.0.1

networks:
  mynetwork:
    external:
      name: bit-env_mynetwork

services:
  das-pay:
    container_name: das-pay-svr
    build:
      context: ./das-pay
      dockerfile: Dockerfile
    image: das-pay
    restart: always
    working_dir: /app
    entrypoint: [ "/app/das-pay", "--config", "/app/config/config.yaml" ]
    volumes:
      - ./das-pay/config:/app/config
    networks:
      - mynetwork


# docker-compose -f docker-compose-pay.yaml up
# docker build .
# docker logs -f --tail=10 das-pay-svr